version: '3.3'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENVIRONMENT: prod
    ports:
      - "8080:80"
    depends_on:
      - backend  # Asegura que el backend se inicie antes del frontend

  backend:
    build:
      context: ../BACK-MASCOTAP  # Contexto para el backend está en la raíz del proyecto backend
      dockerfile: Dockerfile  # Asegúrate de que el Dockerfile está en la raíz del proyecto backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE=${PROD_DATABASE_URL}
      - TOKEN_SECRET=${PROD_TOKEN_SECRET}
